#!/bin/bash

action=$1
action2=$2
shift

[ "$action" = "usage" ] && {
  echo "  Recently comlpeted tasks:"
  echo "    drive"
  echo "      generates a list of completed tasks during the last 7 days."
  echo "      Required argument (String) push or pull."
  echo ""
  exit
}

[ "$action" = "drive" ] && {
     #groovy ~/.todo.actions.d/lately+.groovy "$TODO_DIR" $flag $project
     #groovyclient ~/.todo.actions.d/lately+.groovy "$TODO_DIR" $flag $project
		 coffee ~/.todo.actions.d/drive.coffee "$TODO_DIR" $action2
}
