#!/bin/bash

action=$1
flag=$2
shift

[ "$action" = "usage" ] && {
  echo "  Reprioritize multiple tasks:"
  echo "    mpri"
  echo "      Required argument (integer) list of task numbers."
	echo "      Optional argument (String) priority."
  echo ""
  exit
}

[ "$action" = "mpri" ] && {
		 coffee ~/.todo.actions.d/mpri.coffee "$TODO_DIR" $flag ${@:2}
}
