#!/bin/bash

action=$1
flag=$2
shift

[ "$action" = "usage" ] && {
  echo "  Deprioritize multiple tasks:"
  echo "    dempri"
  echo "      Required argument (integer) list of task numbers."
  echo ""
  exit
}

[ "$action" = "dempri" ] && {
		 coffee ~/.todo.actions.d/dempri.coffee "$TODO_DIR" $flag ${@:2}
}
