#!/bin/bash

action=$1
flag=$2
project=$3
shift

[ "$action" = "usage" ] && {
  echo "  Compile weekly status items and create template email:"
  echo "    weekly-status"
  echo "      generates a list of completed tasks and upcoming tasks between the two dates."
  echo "      Optional startDate YYYY/MM/DD (default is 7 days ago)"
  echo "      Optional endDate   YYYY/MM/DD (default is 7 days in the future)"
  echo ""
  exit
}

[ "$action" = "weekly-status" ] && {
     coffee ~/.todo.actions.d/weekly-status.coffee "$TODO_DIR" $flag $project
}
